version: '3'

networks:
  devnet:
    driver: bridge

services:
 jenkins:
  image: jansiblet
  container_name: jenkins
  ports:
    - "8080:8080"

 gitlab:
   image: gitlab/gitlab-ce:latest
   ports:
     - "8081:80"
     - "8443:443"
   deploy:
     replicas: 1

 sonarqube:
  image: sonarqube
  container_name: sonarqube
  restart: always
  ports:
   - "9000:9000"
  depends_on:
    - sonardb
  links:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
  volumes:
    - "/opt/sonar/:/var/lib/sonar"

 sonardb:
  image: postgres:9.6.1
  container_name: postgres
  restart: always
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
   - POSTGRESQL_DB=sonar
  ports:
    - "5432:5432"
  volumes:
    - "/opt/postgres:/var/lib/postgresql"
  
 nexus:
  image: sonatype/nexus3
  container_name: nexus
  ports:
    - "8082:8081"
  volumes:
    - "/opt/nexus/:/var/lib/nexus"
